name: CI
on:
  workflow_dispatch:
  push:

jobs:
  docker_build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Build
        run: ./docker-build.sh
